# Regresión lineal en Python
## El paquete scikit-learn para Regresión lineal y la selección de rasgos


In [21]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np
import os

In [22]:
mainpath= "d:/python-ml-course-master/datasets"
filename= "ads/Advertising.csv"
fullpath =os.path.join(mainpath, filename)
data = pd.read_csv(fullpath)
data.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [23]:
feature_cols= ["TV", "Radio", "Newspaper"]

In [24]:
x = data[feature_cols]
y = data["Sales"]

In [25]:
estimator = SVR(kernel= "linear")
selector = RFE(estimator, 2, step=1)
selector = selector.fit(x,y)

In [26]:
selector.support_

array([ True,  True, False])

In [27]:
selector.ranking_

array([1, 1, 2])

In [28]:
from sklearn.linear_model import LinearRegression

In [30]:
x_pred = x[["TV","Radio"]]

In [31]:
lm = LinearRegression()
lm.fit(x_pred,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [32]:
lm.intercept_

2.921099912405138

In [33]:
lm.coef_

array([0.04575482, 0.18799423])

In [34]:
lm.score(x_pred, y)

0.8971942610828956